import type { Metadata } from "next";
import { ing115 } from "./Components/lifonts/localfonts";
import "./globals.css";
export const metadata: Metadata = { title: "Create Next App", description: "Generated by create next app", };
export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
      <body className={`${ing115.className} antialiased`} > {children} </body>
    </html>
  );
}
